<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <Version>2025.01.13.1</Version>
    <OutputTarget>Library</OutputTarget>
    <OutputType>Library</OutputType>
    <GenerateSerializationAssemblies>Auto</GenerateSerializationAssemblies>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
    <Title>DigitalRune TextEditor Control</Title>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Description>An open source .NET text editor control for Windows Forms (.NET + .NET Framework)</Description>
    <PackageIcon>logo_64x64.png</PackageIcon>
    <Company>CompuMaster</Company>
    <Product>DigitalRune TextEditor Control</Product>
    <Copyright>Licensed under the GNU Lesser General Public License (LGPL-2.1).</Copyright>
    <PackageProjectUrl>https://github.com/CompuMasterGmbH/CompuMaster.Windows.Forms.DigitalRuneTextEditor</PackageProjectUrl>
    <PackageTags>CompuMaster;Windows;Forms;TextEditor;DigitalRune;TextEditor</PackageTags>
    <PackageLicenseExpression>LGPL-2.1-only</PackageLicenseExpression>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <GenerateResourceUsePreserializedResources>True</GenerateResourceUsePreserializedResources>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DefineConstants>DEBUG;DATACONSISTENCYTEST</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="GUI\Completion\CompletionListView.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_EditActions.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_Update.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_Completion.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_Insight.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_Printing.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_TextEditorProperties.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_ToolTips.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextArea.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextEditorControl_Base.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="GUI\TextAreaControl.cs">
      <SubType>Component</SubType>
    </Compile>
    <Compile Update="GUI\HRuler.cs">
      <SubType>Component</SubType>
    </Compile>
    <EmbeddedResource Include="Resources\ASPX.xshd" />
    <EmbeddedResource Include="Resources\BAT-Mode.xshd" />
    <EmbeddedResource Include="Resources\CPP-Mode.xshd" />
    <EmbeddedResource Include="Resources\Coco-Mode.xshd" />
    <EmbeddedResource Include="Resources\CSharp-Mode.xshd" />
    <EmbeddedResource Include="Resources\HTML-Mode.xshd" />
    <EmbeddedResource Include="Resources\HLSL-Mode.xshd" />
    <EmbeddedResource Include="Resources\Cg-Mode.xshd" />
    <EmbeddedResource Include="Resources\TextEditorControl.bmp" />
    <EmbeddedResource Include="Resources\Java-Mode.xshd" />
    <EmbeddedResource Include="Resources\JavaScript-Mode.xshd" />
    <EmbeddedResource Include="Resources\Mode.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\PHP-Mode.xshd" />
    <EmbeddedResource Include="Resources\RightArrow.cur" />
    <EmbeddedResource Include="Resources\SyntaxModes.xml" />
    <EmbeddedResource Include="Resources\Tex-Mode.xshd" />
    <EmbeddedResource Include="Resources\VBNET-Mode.xshd" />
    <EmbeddedResource Include="Resources\XML-Mode.xshd" />
    <EmbeddedResource Include="Resources\Boo.xshd" />
    <EmbeddedResource Include="Resources\Patch-Mode.xshd" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Resources\SQL-Mode.xshd" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="..\LICENSE">
      <Link>LICENSE</Link>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Include="..\logo_64x64.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>
</Project>