<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>DigitalRune.Windows.SampleEditor</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Copyright>Copyright© 2007-2011 Garstenauer Information Technology OG</Copyright>
    <GenerateResourceUsePreserializedResources>True</GenerateResourceUsePreserializedResources>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalRune.Windows.TextEditor\CompuMaster.Windows.Forms.DigitalRuneTextEditor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Resources.Extensions" Version="9.0.0" />
  </ItemGroup>
</Project>