<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <OutputType>WinExe</OutputType>
    <RootNamespace>DigitalRune.Windows.SampleEditor</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <Copyright>Copyright© 2007-2011 Garstenauer Information Technology OG</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DigitalRune.Windows.TextEditor\DigitalRune.Windows.TextEditor.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Properties\Resources.Designer.cs" />
  </ItemGroup>
</Project>